package service

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/4yrg/gradeloop-core-v2/apps/services/cipas/cipas-xai/internal/client"
	"github.com/4yrg/gradeloop-core-v2/apps/services/cipas/cipas-xai/internal/dto"
	"go.uber.org/zap"
)

// ReasonService handles reasoning operations
type ReasonService struct {
	llmClient client.LLMClient
	logger    *zap.Logger
}

// NewReasonService creates a new reason service
func NewReasonService(llmClient client.LLMClient, logger *zap.Logger) *ReasonService {
	return &ReasonService{
		llmClient: llmClient,
		logger:    logger,
	}
}

// GetReason generates reasoning for the given code and type
func (s *ReasonService) GetReason(ctx context.Context, req dto.ReasonRequest) (*dto.ReasonResponse, error) {
	systemPrompt := `You are an expert computer science professor specializing in Explainable AI (XAI) for code plagiarism and AI-generated code detection. Your goal is to explain *why* the provided code snippets are classified as a specific type of plagiarism or AI-generated. Use concrete evidence from the code. Do not hallucinate or guess; rely only on the provided code.
You MUST return your response as a raw JSON object with no markdown formatting, exactly matching this structure:
{
  "reason": "A detailed paragraph explaining why the code matches the classification, quoting specific variables, structures, or patterns."
}`

	userPrompt := s.buildUserPrompt(req)

	messages := []dto.ChatMessage{
		{Role: "system", Content: systemPrompt},
		{Role: "user", Content: userPrompt},
	}

	resp, err := s.llmClient.SendChat(ctx, messages)
	if err != nil {
		return nil, fmt.Errorf("calling LLM: %w", err)
	}

	// Clean JSON response (remove markdown if any)
	cleanContent := strings.TrimSpace(resp.Content)
	cleanContent = strings.TrimPrefix(cleanContent, "```json")
	cleanContent = strings.TrimPrefix(cleanContent, "```")
	cleanContent = strings.TrimSuffix(cleanContent, "```")
	cleanContent = strings.TrimSpace(cleanContent)

	var llmResp dto.LLMReasonResponse
	if err := json.Unmarshal([]byte(cleanContent), &llmResp); err != nil {
		s.logger.Error("failed to unmarshal LLM response", zap.Error(err), zap.String("content", resp.Content))
		return nil, fmt.Errorf("parsing LLM response: %w", err)
	}

	return &dto.ReasonResponse{
		Reason: llmResp.Reason,
	}, nil
}

func (s *ReasonService) buildUserPrompt(req dto.ReasonRequest) string {
	typeDefinitions := map[string]string{
		"TYPE-1":  "Type-1 clones are exact clones, typically copy-pasted with only minor changes like whitespace or comments.",
		"TYPE-2":  "Type-2 clones are renamed clones, where identifiers (variable/function names) or literal values have been changed, but the structural logic remains identical.",
		"TYPE-3":  "Type-3 clones are modified clones, where statements have been added, removed, or refactored, but the core logic is clearly derived from a common source.",
		"TYPE-4":  "Type-4 clones are semantic clones, sharing the same functionality and logic but implemented with different syntax or algorithms.",
		"TYPE-AI": "Type-AI indicates that the code was likely generated by a Large Language Model (LLM), often characterized by generic patterns, lack of context-specific idiosyncrasies, or overly verbose documentation.",
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("I have analyzed the following code and classified it as %s. %s\n\n", req.Type, typeDefinitions[req.Type]))

	for i, code := range req.Code {
		sb.WriteString(fmt.Sprintf("Snippet %d:\n```\n%s\n```\n\n", i+1, code))
	}

	if req.Type == "TYPE-AI" {
		sb.WriteString("Please provide a detailed reason explaining why this snippet exhibits characteristics of AI-generated code. Quote specific parts of the code to support your claim.")
	} else {
		sb.WriteString(fmt.Sprintf("Please provide a detailed reason explaining why these snippets are a %s clone. Quote specific variables, structural similarities, or logical patterns to support your claim.", req.Type))
	}

	return sb.String()
}
