services:
  # Traefik - API Gateway
  traefik:
    image: traefik:v3.6.1
    container_name: gradeloop-gateway-dev
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # Metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      # Tracing
      - "--tracing.otlp=true"
      - "--tracing.otlp.grpc.endpoint=jaeger:4317"
      - "--tracing.otlp.grpc.insecure=true"
      # Enable JWT Validator Plugin
      # - "--experimental.plugins.jwt-validator.moduleName=github.com/Luka-S/traefik-jwt-validator"
      # - "--experimental.plugins.jwt-validator.version=v1.1.0"
      # Retry configuration for resilience
      - "--providers.docker.watch=true"
    ports:
      - "80:80"
      - "8080:8080" # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - gradeloop-network
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis - In-Memory Cache for Rate Limiting
  redis:
    image: redis:7-alpine
    container_name: gradeloop-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 5s
      retries: 15
    networks:
      - gradeloop-network

  # RabbitMQ - Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: gradeloop-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
      RABBITMQ_DEFAULT_VHOST: "gradeloop"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - gradeloop-network

  # Email Notify Service
  email-notify-service:
    build:
      context: ../../apps/services/email-notify-service
      dockerfile: Dockerfile
    container_name: gradeloop-email-service
    hostname: email-notify-service
    ports:
      - "8083:8080"
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8080"
      RABBITMQ_URL: "amqp://admin:admin123@rabbitmq:5672/gradeloop"
      RABBITMQ_EXCHANGE: "gradeloop.events"
      RABBITMQ_QUEUE: "email.notifications"
      # Load from .env at root
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - gradeloop-network
    restart: unless-stopped

  # IAM Service - Identity and Access Management
  iam-service:
    build:
      context: ../../
      dockerfile: apps/services/iam-service/Dockerfile
    container_name: gradeloop-iam-service-dev
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.iam.loadbalancer.server.port=3000"

      # Public IAM Routes (Auth endpoints that don't require JWT)
      - "traefik.http.routers.iam-public.rule=PathPrefix(`/api/iam/v1/auth/login`) || PathPrefix(`/api/iam/v1/auth/refresh`) || PathPrefix(`/api/iam/v1/auth/activate`) || PathPrefix(`/api/iam/v1/auth/request-activation`) || PathPrefix(`/api/iam/v1/auth/validate`) || PathPrefix(`/api/iam/health`) || PathPrefix(`/api/iam/metrics`)"
      - "traefik.http.routers.iam-public.entrypoints=web"
      - "traefik.http.routers.iam-public.middlewares=iam-replacepath"

      # Protected IAM Routes (Requires JWT Validation at the Edge)
      - "traefik.http.routers.iam-protected.rule=PathPrefix(`/api/iam`) && !(PathPrefix(`/api/iam/v1/auth/login`) || PathPrefix(`/api/iam/v1/auth/refresh`) || PathPrefix(`/api/iam/v1/auth/activate`) || PathPrefix(`/api/iam/v1/auth/request-activation`) || PathPrefix(`/api/iam/v1/auth/validate`) || PathPrefix(`/api/iam/health`) || PathPrefix(`/api/iam/metrics`))"
      - "traefik.http.routers.iam-protected.entrypoints=web"
      - "traefik.http.routers.iam-protected.middlewares=iam-replacepath"

      # Middlewares
      - "traefik.http.middlewares.iam-replacepath.replacepathregex.regex=^/api/iam(.*)"
      - "traefik.http.middlewares.iam-replacepath.replacepathregex.replacement=/api$$1"

      # JWT Validation via ForwardAuth - Zero Trust Architecture
      - "traefik.http.middlewares.iam-jwt-auth.forwardauth.address=http://iam-service:3000/api/v1/auth/validate"
      - "traefik.http.middlewares.iam-jwt-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.iam-jwt-auth.forwardauth.authResponseHeaders=X-User-Id,X-User-Roles,X-User-Permissions,X-User-Email,X-User-Name"

      # Retry mechanism with backoff for IAM service connection resilience
      - "traefik.http.middlewares.iam-retry.retry.attempts=3"
      - "traefik.http.middlewares.iam-retry.retry.initialInterval=100ms"
    environment:
      DATABASE_URL: ${POSTGRES_URL_BASE}iam_db?sslmode=${POSTGRES_SSLMODE}
      REDIS_ADDR: "redis:6379"
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JAEGER_ENDPOINT: "jaeger:4317"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/iam/health" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    develop:
      watch:
        - action: rebuild
          path: ../../apps/services/iam-service
        - action: rebuild
          path: ../../shared/libs/go/secrets
        - action: rebuild
          path: ../../shared/libs/go/middleware
        - action: rebuild
          path: ../../shared/libs/go/logger
    networks:
      - gradeloop-network

  # Academics Service - Academic Management
  academics-service:
    build:
      context: ../../
      dockerfile: apps/services/academics-service/Dockerfile
    container_name: gradeloop-academics-service-dev
    ports:
      - "3002:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.academics.loadbalancer.server.port=3001"

      # All academics routes require JWT validation
      - "traefik.http.routers.academics.rule=PathPrefix(`/api/academics`)"
      - "traefik.http.routers.academics.entrypoints=web"
      - "traefik.http.routers.academics.middlewares=academics-jwt-auth,academics-replacepath"

      # Middlewares
      - "traefik.http.middlewares.academics-replacepath.replacepathregex.regex=^/api/academics(.*)"
      - "traefik.http.middlewares.academics-replacepath.replacepathregex.replacement=/api$$1"

      # JWT Validation via ForwardAuth
      - "traefik.http.middlewares.academics-jwt-auth.forwardauth.address=http://iam-service:3000/api/v1/auth/validate"
      - "traefik.http.middlewares.academics-jwt-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.academics-jwt-auth.forwardauth.authResponseHeaders=X-User-Id,X-User-Roles,X-User-Permissions,X-User-Email,X-User-Name"
    environment:
      DATABASE_URL: ${POSTGRES_URL_BASE}academics_db?sslmode=${POSTGRES_SSLMODE}
      JAEGER_ENDPOINT: "jaeger:4317"
    depends_on:
      iam-service:
        condition: service_healthy
    networks:
      - gradeloop-network

  # Prometheus - Metrics Collection
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: gradeloop-prometheus-dev
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    networks:
      - gradeloop-network

  # Grafana - Visualization
  grafana:
    image: grafana/grafana:10.4.0
    container_name: gradeloop-grafana-dev
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - gradeloop-network

  # Jaeger - Distributed Tracing
  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: gradeloop-jaeger-dev
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "14250:14250" # Jaeger gRPC
      - "14268:14268" # Jaeger HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - gradeloop-network

networks:
  gradeloop-network:
    name: gradeloop-network
    driver: bridge

volumes:
  rabbitmq-data:
    name: gradeloop-rabbitmq-data
  prometheus-data:
  grafana-data:
  jaeger-data:
