services:
  # Traefik - API Gateway
  traefik:
    image: traefik:v3.6.1
    container_name: gradeloop-gateway-dev
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # Metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      # Tracing
      - "--tracing.otlp=true"
      - "--tracing.otlp.grpc.endpoint=jaeger:4317"
      - "--tracing.otlp.grpc.insecure=true"
      # Retry configuration for resilience
      - "--providers.docker.watch=true"
    ports:
      - "80:80"
      - "8080:8080" # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - gradeloop-network
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # RabbitMQ - Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: gradeloop-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
      RABBITMQ_DEFAULT_VHOST: "gradeloop"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - gradeloop-network

  # Email Notify Service
  email-notify-service:
    build:
      context: ../../apps/services/email-notify-service
      dockerfile: Dockerfile
    container_name: gradeloop-email-service
    hostname: email-notify-service
    ports:
      - "8083:8080"
    env_file:
      - ../../.env
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8080"
      RABBITMQ_URL: "amqp://admin:admin123@rabbitmq:5672/gradeloop"
      RABBITMQ_EXCHANGE: "gradeloop.events"
      RABBITMQ_QUEUE: "email.notifications"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - gradeloop-network
    restart: unless-stopped

  # IAM Service - Identity and Access Management
  iam-service:
    build:
      context: ../../
      dockerfile: apps/services/iam-service/Dockerfile
    container_name: gradeloop-iam-service-dev
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.iam.loadbalancer.server.port=3000"
      - "traefik.http.routers.iam-public.rule=PathPrefix(`/api/iam/v1/auth/login`) || PathPrefix(`/api/iam/v1/auth/refresh`) || PathPrefix(`/api/iam/v1/auth/activate`) || PathPrefix(`/api/iam/v1/auth/request-activation`) || PathPrefix(`/api/iam/v1/auth/validate`) || PathPrefix(`/api/iam/health`) || PathPrefix(`/api/iam/metrics`)"
      - "traefik.http.routers.iam-public.entrypoints=web"
      - "traefik.http.routers.iam-public.middlewares=iam-replacepath"
      - "traefik.http.routers.iam-protected.rule=PathPrefix(`/api/iam`) && !(PathPrefix(`/api/iam/v1/auth/login`) || PathPrefix(`/api/iam/v1/auth/refresh`) || PathPrefix(`/api/iam/v1/auth/activate`) || PathPrefix(`/api/iam/v1/auth/request-activation`) || PathPrefix(`/api/iam/v1/auth/validate`) || PathPrefix(`/api/iam/health`) || PathPrefix(`/api/iam/metrics`))"
      - "traefik.http.routers.iam-protected.entrypoints=web"
      - "traefik.http.routers.iam-protected.middlewares=iam-replacepath"
      - "traefik.http.middlewares.iam-replacepath.replacepathregex.regex=^/api/iam(.*)"
      - "traefik.http.middlewares.iam-replacepath.replacepathregex.replacement=/api$$1"
      - "traefik.http.middlewares.iam-jwt-auth.forwardauth.address=http://iam-service:3000/api/v1/auth/validate"
      - "traefik.http.middlewares.iam-jwt-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.iam-jwt-auth.forwardauth.authResponseHeaders=X-User-Id,X-User-Roles,X-User-Permissions,X-User-Email,X-User-Name"
      - "traefik.http.middlewares.iam-retry.retry.attempts=3"
      - "traefik.http.middlewares.iam-retry.retry.initialInterval=100ms"
    env_file:
      - ../../.env
    environment:
      DATABASE_URL: ${POSTGRES_URL_BASE}iam_db?sslmode=${POSTGRES_SSLMODE}
      REDIS_ADDR: "${REDIS_HOST}:${REDIS_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/iam/health" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    develop:
      watch:
        - action: rebuild
          path: ../../apps/services/iam-service
        - action: rebuild
          path: ../../shared/libs/go/secrets
        - action: rebuild
          path: ../../shared/libs/go/middleware
        - action: rebuild
          path: ../../shared/libs/go/logger
    networks:
      - gradeloop-network

  # Academics Service - Academic Management
  academics-service:
    build:
      context: ../../
      dockerfile: apps/services/academics-service/Dockerfile
    container_name: gradeloop-academics-service-dev
    ports:
      - "3002:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.academics.loadbalancer.server.port=3001"
      - "traefik.http.routers.academics.rule=PathPrefix(`/api/academics`)"
      - "traefik.http.routers.academics.entrypoints=web"
      - "traefik.http.routers.academics.middlewares=academics-jwt-auth,academics-replacepath"
      - "traefik.http.middlewares.academics-replacepath.replacepathregex.regex=^/api/academics(.*)"
      - "traefik.http.middlewares.academics-replacepath.replacepathregex.replacement=/api$$1"
      - "traefik.http.middlewares.academics-jwt-auth.forwardauth.address=http://iam-service:3000/api/v1/auth/validate"
      - "traefik.http.middlewares.academics-jwt-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.academics-jwt-auth.forwardauth.authResponseHeaders=X-User-Id,X-User-Roles,X-User-Permissions,X-User-Email,X-User-Name"
    env_file:
      - ../../.env
    environment:
      DATABASE_URL: ${POSTGRES_URL_BASE}academics_db?sslmode=${POSTGRES_SSLMODE}
    depends_on:
      iam-service:
        condition: service_healthy
    networks:
      - gradeloop-network

networks:
  gradeloop-network:
    name: gradeloop-network
    driver: bridge

volumes:
  rabbitmq-data:
    name: gradeloop-rabbitmq-data
