services:
  # HashiCorp Vault - Secrets Management (Dev Mode)
  vault:
    image: hashicorp/vault:1.15
    container_name: gradeloop-vault-dev
    hostname: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "dev-root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_LOG_LEVEL: "debug"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-audit-logs:/vault/logs
    command: server -dev -dev-root-token-id="dev-root-token"
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gradeloop-network

  # Vault Initializer - Seeds initial secrets on startup
  vault-init:
    image: hashicorp/vault:1.15
    container_name: gradeloop-vault-init
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "dev-root-token"
    volumes:
      - ../../scripts/vault-init.sh:/vault-init.sh:ro
      - ./vault/secrets:/vault/secrets
    command: /bin/sh /vault-init.sh
    networks:
      - gradeloop-network
    restart: "no"

networks:
  gradeloop-network:
    name: gradeloop-network
    driver: bridge

volumes:
  vault-audit-logs:
    name: gradeloop-vault-audit-logs
  postgres-data:
  postgres-secrets:
