services:
  # Traefik - API Gateway
  traefik:
    image: traefik:v3.6.1
    container_name: gradeloop-gateway-dev
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # Retry configuration for resilience
      - "--providers.docker.watch=true"
    ports:
      - "80:80"
      - "8082:8080" # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - gradeloop-network
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3

  # RabbitMQ - Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: gradeloop-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
      RABBITMQ_DEFAULT_VHOST: "gradeloop"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - gradeloop-network



  # JWT Key Generator - Generates RSA keys for JWT signing
  jwt-key-generator:
    image: alpine:latest
    container_name: gradeloop-jwt-keygen
    volumes:
      - ../../.env:/workspace/.env
      - ../../scripts/generate-jwt-keys.sh:/workspace/generate-jwt-keys.sh
    working_dir: /workspace
    command: >
      sh -c "
        if [ -z \"$${JWT_PRIVATE_KEY_BASE64}\" ] || [ -z \"$${JWT_PUBLIC_KEY_BASE64}\" ]; then
          echo 'JWT keys not found in .env, generating new keys...'
          chmod +x generate-jwt-keys.sh
          ./generate-jwt-keys.sh
        else
          echo 'JWT keys already exist in .env, skipping generation'
        fi
      "
    environment:
      - JWT_PRIVATE_KEY_BASE64
      - JWT_PUBLIC_KEY_BASE64
    env_file:
      - ../../.env
    networks:
      - gradeloop-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gradeloop-postgres-dev
    environment:
      POSTGRES_DB: iam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gradeloop-network

  # IAM Service - Identity and Access Management (Spring Boot 4)
  iam-service:
    build:
      context: ../../apps/services/iam-service
      dockerfile: Dockerfile
    container_name: gradeloop-iam-service-dev
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.iam.loadbalancer.server.port=8080"
      # Public endpoints (no authentication required)
      - "traefik.http.routers.iam-public.rule=PathPrefix(`/api/v1/auth`) || PathPrefix(`/health`) || PathPrefix(`/actuator`)"
      - "traefik.http.routers.iam-public.entrypoints=web"
      - "traefik.http.routers.iam-public.service=iam"
      # Protected endpoints (require authentication)
      - "traefik.http.routers.iam-protected.rule=PathPrefix(`/api/v1`) && !PathPrefix(`/api/v1/auth`)"
      - "traefik.http.routers.iam-protected.entrypoints=web"
      - "traefik.http.routers.iam-protected.service=iam"
      - "traefik.http.routers.iam-protected.middlewares=iam-auth"
      # Authentication middleware
      - "traefik.http.middlewares.iam-auth.forwardauth.address=http://iam-service:8080/actuator/health"
      - "traefik.http.middlewares.iam-auth.forwardauth.trustForwardHeader=true"
      # Retry middleware for resilience
      - "traefik.http.middlewares.iam-retry.retry.attempts=3"
      - "traefik.http.middlewares.iam-retry.retry.initialInterval=100ms"
    env_file:
      - ../../.env
    environment:
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: iam_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SSLMODE: disable
      # JWT Configuration
      JWT_SECRET: gradeloop_dev_secret_32_chars_long_!!
      # Server Configuration
      SERVER_PORT: 8080
      # JWT Configuration (RSA keys should be base64 encoded)
      JWT_PRIVATE_KEY_BASE64: ${JWT_PRIVATE_KEY_BASE64:-}
      JWT_PUBLIC_KEY_BASE64: ${JWT_PUBLIC_KEY_BASE64:-}
      # Initial Admin Configuration
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL:-admin@example.com}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD:-Admin@123}
      # Logging
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_GRADELOOP_IAM_SERVICE: DEBUG
    depends_on:
      jwt-key-generator:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    develop:
      watch:
        - action: rebuild
          path: ../../apps/services/iam-service
    networks:
      - gradeloop-network
    restart: unless-stopped




networks:
  gradeloop-network:
    name: gradeloop-network
    driver: bridge

volumes:
  rabbitmq-data:
    name: gradeloop-rabbitmq-data
  postgres-data:
    name: gradeloop-postgres-data
